### ISSUE TITLE
有没有大佬遇到过这个问题：CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by DannyLinjx** [qi-hua/async_cosyvoice#110]
4090卡跑的，具体错误是下面，目前不清楚是我没改哪里还是源代码有问题

Traceback (most recent call last):
  File "CosyVoice/async_cosyvoice/runtime/async_grpc/server.py", line 76, in Inference
    async for response in self._handle_generic(request, processor, processor_args):
  File "CosyVoice/async_cosyvoice/runtime/async_grpc/server.py", line 209, in _handle_generic
    async for model_chunk in processor(*processor_args):
  File "CosyVoice/async_cosyvoice/runtime/async_grpc/../../../async_cosyvoice/async_cosyvoice.py", line 99, in inference_zero_shot
    model_input = self.frontend.frontend_zero_shot(i, prompt_text, prompt_speech_16k, self.sample_rate)
  File "CosyVoice/async_cosyvoice/runtime/async_grpc/../../../async_cosyvoice/frontend.py", line 347, in frontend_zero_shot
    speech_feat, speech_feat_len = self._extract_speech_feat(prompt_speech_resample)
  File CosyVoice/async_cosyvoice/runtime/async_grpc/../../../async_cosyvoice/frontend.py", line 294, in _extract_speech_feat
    speech_feat = self.feat_extractor(speech).squeeze(dim=0).transpose(0, 1).to(self.device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by wenyangchou** [comment]
啥原因？为什么就关闭了？

**Comment by DannyLinjx** [comment]
> 啥原因？为什么就关闭了？

已经解决了，是并发量问题，过大会导致部分内存没释放会混乱，调小就行了，可能作者这方面代码没处理好

**Comment by wenyangchou** [comment]
> > 啥原因？为什么就关闭了？
> 
> 已经解决了，是并发量问题，过大会导致部分内存没释放会混乱，调小就行了，可能作者这方面代码没处理好

`gpu_memory_utilization`参数吗？我一开始猜测是内存原因，但是发现这个问题不是必现，我设置一个0.55，一个0.5，同样的卡上。结果今天0.5 的出现了这个问题。并且在后续压测时无法精准必现

**Comment by DannyLinjx** [comment]
> > > 啥原因？为什么就关闭了？
> > 
> > 
> > 已经解决了，是并发量问题，过大会导致部分内存没释放会混乱，调小就行了，可能作者这方面代码没处理好
> 
> `gpu_memory_utilization`参数吗？我一开始猜测是内存原因，但是发现这个问题不是必现，我设置一个0.55，一个0.5，同样的卡上。结果今天0.5 的出现了这个问题。并且在后续压测时无法精准必现

不是，这个只是使用的显存比例而已，是max_conc大小

**Comment by wenyangchou** [comment]
> > > > 啥原因？为什么就关闭了？
> > > 
> > > 
> > > 已经解决了，是并发量问题，过大会导致部分内存没释放会混乱，调小就行了，可能作者这方面代码没处理好
> > 
> > 
> > `gpu_memory_utilization`参数吗？我一开始猜测是内存原因，但是发现这个问题不是必现，我设置一个0.55，一个0.5，同样的卡上。结果今天0.5 的出现了这个问题。并且在后续压测时无法精准必现
> 
> 不是，这个只是使用的显存比例而已，是max_conc大小

这个参数是控制RPC客户端连接数量？对应到restapi上就是并发数？ 大佬，这个异常你能必现吗

**Comment by DannyLinjx** [comment]
> > > > > 啥原因？为什么就关闭了？
> > > > 
> > > > 
> > > > 已经解决了，是并发量问题，过大会导致部分内存没释放会混乱，调小就行了，可能作者这方面代码没处理好
> > > 
> > > 
> > > `gpu_memory_utilization`参数吗？我一开始猜测是内存原因，但是发现这个问题不是必现，我设置一个0.55，一个0.5，同样的卡上。结果今天0.5 的出现了这个问题。并且在后续压测时无法精准必现
> > 
> > 
> > 不是，这个只是使用的显存比例而已，是max_conc大小
> 
> 这个参数是控制RPC客户端连接数量？对应到restapi上就是并发数？ 大佬，这个异常你能必现吗

是，这个就是控制并发，客户端口默认值有点偏大了，你可以调小点，我目前只是调小了还没空改代码，调小之后速度会慢些

**Comment by wenyangchou** [comment]
> > > > > > 啥原因？为什么就关闭了？
> > > > > 
> > > > > 
> > > > > 已经解决了，是并发量问题，过大会导致部分内存没释放会混乱，调小就行了，可能作者这方面代码没处理好
> > > > 
> > > > 
> > > > `gpu_memory_utilization`参数吗？我一开始猜测是内存原因，但是发现这个问题不是必现，我设置一个0.55，一个0.5，同样的卡上。结果今天0.5 的出现了这个问题。并且在后续压测时无法精准必现
> > > 
> > > 
> > > 不是，这个只是使用的显存比例而已，是max_conc大小
> > 
> > 
> > 这个参数是控制RPC客户端连接数量？对应到restapi上就是并发数？ 大佬，这个异常你能必现吗
> 
> 是，这个就是控制并发，客户端口默认值有点偏大了，你可以调小点，我目前只是调小了还没空改代码，调小之后速度会慢些

感觉。。。不是你说的这个原因，内存不够报了其他错：
```
torch.OutOfMemoryError: CUDA out of memory. 
```
内存越界：
```
CUDA error: an illegal memory access was encountered
```
好像是代码逻辑问题导致的bug。看GPT的解法，感觉跟另一个issue解决方案很像

**Comment by DannyLinjx** [comment]
> > > > > > > 啥原因？为什么就关闭了？
> > > > > > 
> > > > > > 
> > > > > > 已经解决了，是并发量问题，过大会导致部分内存没释放会混乱，调小就行了，可能作者这方面代码没处理好
> > > > > 
> > > > > 
> > > > > `gpu_memory_utilization`参数吗？我一开始猜测是内存原因，但是发现这个问题不是必现，我设置一个0.55，一个0.5，同样的卡上。结果今天0.5 的出现了这个问题。并且在后续压测时无法精准必现
> > > > 
> > > > 
> > > > 不是，这个只是使用的显存比例而已，是max_conc大小
> > > 
> > > 
> > > 这个参数是控制RPC客户端连接数量？对应到restapi上就是并发数？ 大佬，这个异常你能必现吗
> > 
> > 
> > 是，这个就是控制并发，客户端口默认值有点偏大了，你可以调小点，我目前只是调小了还没空改代码，调小之后速度会慢些
> 
> 感觉。。。不是你说的这个原因，内存不够报了其他错：
> 
> ```
> torch.OutOfMemoryError: CUDA out of memory. 
> ```
> 
> 内存越界：
> 
> ```
> CUDA error: an illegal memory access was encountered
> ```
> 
> 好像是代码逻辑问题导致的bug。看GPT的解法，感觉跟另一个issue解决方案很像

首先，你这个是oom，这是你显存问题，自己把gpu_memory_utilization调小调回去，其次，我说了我这个是并发量问题，先搞清楚你的报错点在哪，还有你如果说感觉不是我这个原因的话，那你在这问干什么
