### ISSUE TITLE
在压测的时候遇到了一个错误，RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [qi-hua/async_cosyvoice#75]
```
2025-04-21 04:24:14,202 DEBUG Processing with inference_zero_shot_by_spk_id


  0%|          | 0/1 [00:00<?, ?it/s][A2025-04-21 04:24:14,232 INFO synthesis text 用户可能是在购买或自制这种粽子后，想知道能保存多久，避免食物浪费或者食有明确说明保存方式。
2025-04-21 04:24:14,232 INFO llm job done, generated  355 tokens, time cost: 2.312s
2025-04-21 04:24:14,233 DEBUG speech_tokens: len: 355  data: [1788, 3732, 5838, 5838, 5919, 5919, 5109, 2922, 1869, 4299, 1761, 4676, 2499, 2573, 89, 59, 1587, 1887, 1839, 29, 4456, 4545, 5286, 6261, 2244, 3240, 2757, 3644, 1457, 728, 725, 1457, 5102, 5097, 2113, 1948, 1701, 3888, 5835, 5835, 3648, 1788, 5940, 6048, 2403, 4616, 887, 1032, 5319, 1538, 890, 890, 890, 809, 3077, 3805, 5988, 4576, 4570, 4966, 4966, 4994, 970, 2166, 66, 557, 1808, 5526, 5526, 786, 5020, 2752, 386, 8, 8, 32, 4415, 2307, 3894, 5106, 2922, 1464, 1959, 4210, 1376, 1376, 808, 6379, 6374, 5419, 2261, 1041, 4679, 3238, 3482, 1295, 1295, 2510, 4071, 4314, 821, 8, 359, 2807, 4992, 5019, 4607, 515, 710, 710, 710, 719, 1434, 2112, 1674, 4940, 4769, 4490, 4507, 5208, 4416, 5483, 2256, 5192, 4699, 5608, 5041, 3771, 5021, 566, 35, 8, 41, 4421, 4500, 3981, 4299, 3651, 5109, 5109, 5838, 5109, 3645, 1944, 1947, 1703, 1625, 5324, 228, 4922, 2274, 2456, 152, 116, 8, 2195, 1788, 5919, 3652, 2112, 3777, 5991, 5335, 4576, 4579, 4723, 5695, 5722, 4992, 5019, 2428, 5986, 4382, 3647, 992, 2050, 171, 4484, 951, 54, 647, 1970, 5527, 2127, 2400, 4850, 35, 1644, 2976, 3144, 5261, 159, 4920, 5750, 4769, 4490, 4409, 4495, 3012, 1707, 5838, 3651, 735, 2112, 60, 5319, 2397, 4605, 5344, 3077, 1842, 66, 2909, 5093, 5084, 5050, 4816, 1944, 3159, 3648, 1060, 1960, 3481, 137, 716, 1616, 2014, 5100, 5019, 404, 786, 2760, 2202, 3656, 1946, 1946, 1220, 602, 5090, 2139, 2160, 3292, 4939, 4517, 4517, 4750, 4804, 4432, 5729, 2472, 5188, 2773, 4879, 5527, 1587, 404, 35, 2370, 1779, 4519, 64, 303, 3240, 2841, 2186, 1457, 1457, 2186, 1457, 5829, 4363, 2113, 4299, 4299, 4299, 3894, 5838, 5838, 5109, 2193, 1464, 2112, 6379, 4437, 4460, 5840, 2573, 2833, 565, 191, 626, 710, 719, 3644, 1447, 4299, 2166, 2863, 6481, 6084, 6156, 4536, 1893, 0, 4439, 145, 1761, 160, 1267, 4316, 6259, 60, 2834, 89, 8, 1587, 1914, 144, 737, 2999, 4457, 1083, 5835, 5109, 735, 4299, 2112, 2733, 4432, 3562, 2834, 278, 35, 1560, 1564, 2175, 66, 1466, 5189, 4522, 6018, 1770, 3240, 5754, 1420, 2186, 2105, 2186, 5828, 1206, 5889, 3879, 5086, 5043, 5775]

  0%|          | 0/1 [00:02<?, ?it/s]
2025-04-21 04:24:14,444 ERROR Request processing failed: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
    Traceback (most recent call last):
  File "/workspace/async_cosyvoice/runtime/async_grpc/server.py", line 58, in Inference
    async for response in self._handle_generic(request, processor, processor_args):
  File "/workspace/async_cosyvoice/runtime/async_grpc/server.py", line 179, in _handle_generic
    async for model_chunk in processor(*processor_args):
  File "/workspace/async_cosyvoice/runtime/async_grpc/../../../async_cosyvoice/async_cosyvoice.py", line 138, in inference_zero_shot_by_spk_id
    async for model_output in self.model.async_tts(**model_input, stream=stream, speed=speed):
  File "/workspace/async_cosyvoice/runtime/async_grpc/../../../async_cosyvoice/model.py", line 349, in async_tts
    this_tts_speech = await loop.run_in_executor(self.thread_executor,
  File "/root/miniconda3/envs/cosyvoice2/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/async_cosyvoice/runtime/async_grpc/../../../async_cosyvoice/model.py", line 258, in token2wav
    tts_mel, _ = self.flow.inference(token=token.to(self.device),
  File "/root/miniconda3/envs/cosyvoice2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/async_cosyvoice/runtime/async_grpc/../../../cosyvoice/flow/flow.py", line 230, in inference
    feat, _ = self.decoder(
  File "/root/miniconda3/envs/cosyvoice2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cosyvoice2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cosyvoice2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/async_cosyvoice/runtime/async_grpc/../../../cosyvoice/flow/flow_matching.py", line 267, in forward
    return self.solve_euler(z, t_span=t_span, mu=mu, mask=mask, spks=spks, cond=cond), None
  File "/workspace/async_cosyvoice/runtime/async_grpc/../../../cosyvoice/flow/flow_matching.py", line 130, in solve_euler
dphi_dt = self.forward_estimator(
  File "/workspace/async_cosyvoice/runtime/async_grpc/../../../cosyvoice/flow/flow_matching.py", line 174, in forward_estimator
    torch.cuda.current_stream().synchronize()
  File "/root/miniconda3/envs/cosyvoice2/lib/python3.10/site-packages/torch/cuda/streams.py", line 100, in synchronize
    super().synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by CallmeZhangChenchen** [comment]
然后，就是所有的请求都不会返回结果

**Comment by zhangxuewei1989** [comment]
我也遇到了这个问题

**Comment by CallmeZhangChenchen** [comment]
跟 TensorRT 有关系，
直接把 *.mygpu.plan 删了，让工程自动生成这个文件，就很难复现了

**Comment by CallmeZhangChenchen** [comment]
重新生成了 fp16.mygpu.plan，出现问题情况会减少，但是偶尔还是会有

**Comment by CallmeZhangChenchen** [comment]
嗯嗯，感谢回复！
使用 1 个estimator，原则上应该会很稳定，
但是使用1 个estimator 4 个并发的情况，会比使用 2个estimator 4 个并发，首音耗时平均增加一倍 

请问，您这边有怀疑的地方吗？关于这个非法内存访问

会不会跟显存一直增加有关系呢

**Comment by CallmeZhangChenchen** [comment]
加了个，torch.cuda.empty_cache() 显存不增加了， 貌似跟这个也没关系

会不会更 tensorrt的安装方式有关系   
或者 我试试 使用 tensorrt v2 的同步接口吧，

**Comment by qi-hua** [comment]
目前我使用的是原本的一个estimator /xk/xk没有遇到这个问题，不确定在torch定期清理显存后还是否会存在这个问题，不好意思，我不太了解这里的原因。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年4月25日(周五) 中午12:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qi-hua/async_cosyvoice] 在压测的时候遇到了一个错误，RuntimeError: CUDA error: an illegal memory access was encountered (Issue #75)


 CallmeZhangChenchen left a comment (qi-hua/async_cosyvoice#75)
 
嗯嗯，感谢回复！
 使用 1 个estimator，原则上应该会很稳定，
 但是使用1 个estimator 4 个并发的情况，会比使用 2个estimator 4 个并发，首音耗时平均增加一倍
 
请问，您这边有怀疑的地方吗？关于这个非法内存访问
 
会不会跟显存一直增加有关系呢

**Comment by hexisyztem** [comment]
通常是显存不足导致的问题，请减少 Estimator 的数量或者参考这里减少单个Estimator context 的显存占用：https://github.com/FunAudioLLM/CosyVoice/blob/dev/Comet/cosyvoice/utils/file_utils.py#L64

**Comment by Artrajz** [comment]
> 通常是显存不足导致的问题，请减少 Estimator 的数量或者参考这里减少单个Estimator context 的显存占用：https://github.com/FunAudioLLM/CosyVoice/blob/dev/Comet/cosyvoice/utils/file_utils.py#L64

我这边在async_tts最后用 `finally` 添加`torch.cuda.empty_cache()`，使用`estimator_count=1`，Estimator context 的显存占用没改，在长时间运行后仍有概率会出现这个问题，从正常开始运行到出问题的时间不固定（复现可能存在困难）。显卡是4090 24g的，运行时显存占用稳定在21500MB以下。出现这个问题后通常会导致其他请求任务也无法正常推理，目前我只能通过不断重启来解决。

这是我这边的情况，希望能辅助大佬分析问题

**Comment by brooks348** [comment]
报这个错的时候显存还剩余很多，这个是显存的问题吗

**Comment by brooks348** [comment]
题主 有解决这个问题吗

**Comment by CallmeZhangChenchen** [comment]
我看不到你这个评论了，后来你删掉了吗？请问是已经解决了嘛


2769904765
***@***.***



        



         原始邮件
         
       
发件人：Artrajz ***@***.***&gt;
发件时间：2025年5月1日 12:35
收件人：qi-hua/async_cosyvoice ***@***.***&gt;
抄送：CallmeZhangChenchen ***@***.***&gt;, Author ***@***.***&gt;
主题：Re: [qi-hua/async_cosyvoice] 在压测的时候遇到了一个错误，RuntimeError: CUDA error: an illegal memory access was encountered (Issue #75)



Artrajz left a comment (qi-hua/async_cosyvoice#75)

通常是显存不足导致的问题，请减少 Estimator 的数量或者参考这里减少单个Estimator context 的显存占用：https://github.com/FunAudioLLM/CosyVoice/blob/dev/Comet/cosyvoice/utils/file_utils.py#L64

我这边在async_tts最后用 finally&nbsp;添加torch.cuda.empty_cache()，使用estimator_count=1，Estimator context 的显存占用没改，在长时间运行后仍有概率会出现这个问题，从正常开始运行到出问题的时间不固定（复现可能存在困难）。显卡是4090 24g的，运行时显存占用稳定在21500MB以下。出现这个问题后通常会导致其他请求任务也无法正常推理，目前我只能通过不断重启来解决。

这是我这边的情况，希望能辅助大佬分析问题

**Comment by CallmeZhangChenchen** [comment]
> 题主 有解决这个问题吗

还没，很难复现，只有在程序启动之后的的几十次调用中容易复现
为了避免服务卡死，现在只能加个 try catch捕获RuntimeError，然后重启

**Comment by brooks348** [comment]
我这边发现和线程数有关系，a100显卡，开十线基本上必线。另外我发现将model.py 中的thread_count=10 中的这个子线程改成1 就不会再出现。

![Image](https://github.com/user-attachments/assets/c279de6b-b6ab-4580-97b2-7823034c9ed4)

**Comment by CallmeZhangChenchen** [comment]
> 我这边发现和线程数有关系，a100显卡，开十线基本上必线。另外我发现将model.py 中的strean_scale_factor=10 中的这个子线程改成1 就不会再出现。
> 
> ![Image](https://github.com/user-attachments/assets/b990daf5-a03d-49b4-8cb9-9c0e8fa66b27)

https://github.com/qi-hua/async_cosyvoice/blob/9b87415f1e8fd04a911844c1cfe62f165d53c35d/model.py#L99
你们是不是做过什么改动，这里代码写的本来就是 1

**Comment by zhuangzhuangliu2345** [comment]
我拉下最新的model 试下。

**Comment by hexisyztem** [comment]
你们这里提到的问题比较像是之前修复过的一个问题，确认是拉取了最新的代码吗？

**Comment by brooks348** [comment]
抱歉，上午说错了，是thread_count这个子线程的个数，会影响内存的使用。

**Comment by hexisyztem** [comment]
> 抱歉，上午说错了，是thread_count这个子线程的个数，会影响内存的使用。

thread count 只会影响运行时的显存，也就是说目前预留下来的显存空间不足以让程序稳定运行。建议考虑减少 estimator count 的数量，或者是减少单个 esitmator context 所需要的显存空间。

参考：
# 限制 estimator 内存方法 
# 原本代码编译后的flow trt模型 显存占用4.6G过大，修改为 1.6G，便于启动多个 estimator 实例，并发推理。
# 修改 cosyvoice/utils/file_utils.py:64
#     # config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 33)  # 8GB
#     config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)  # 1GB
# 删除已经编译的模型./pretrained_models/CosyVoice2-0.5B/flow.decoder.estimator.fp16.mygpu.plan
# 重新运行服务器代码  --trt 将重新编译模型，到时将生成新的模型，并单个 estimator 只占用 1.6GB 显存
# 根据GPU显存大小量及性能设置合适的 ESTIMATOR_COUNT

**Comment by hexisyztem** [comment]
> 抱歉，上午说错了，是thread_count这个子线程的个数，会影响内存的使用。

```
# 限制 estimator 内存方法
# 原本代码编译后的flow trt模型 显存占用4.6G过大，修改为 1.6G，便于启动多个 estimator 实例，并发推理。
# 修改 cosyvoice/utils/file_utils.py:64
#     # config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 33)  # 8GB
#     config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)  # 1GB
# 删除已经编译的模型./pretrained_models/CosyVoice2-0.5B/flow.decoder.estimator.fp16.mygpu.plan
# 重新运行服务器代码  --trt 将重新编译模型，到时将生成新的模型，并单个 estimator 只占用 1.6GB 显存
# 根据GPU显存大小量及性能设置合适的 ESTIMATOR_COUNT
```

**Comment by brooks348** [comment]
好的，感谢大佬回答。这个非法内存感觉还是和显存有关系，我在不开fp16的时候出现的概率很大，相同的配置。
打开以后就没出现过了/。

**Comment by brooks348** [comment]
> 你们这里提到的问题比较像是之前修复过的一个问题，确认是拉取了最新的代码吗？

您指的是model里面针对末尾6561 之类的处理那次更改吗。

**Comment by CallmeZhangChenchen** [comment]
@hexisyztem 感谢回复！  我尽量把问题描述清楚

我们上午在讨论如何避免 RuntimeError 错误发生的问题，
提到 “ 将model.py 中的thread_count=10 中的这个子线程改成1 就不会再出现”，这个我将会测试看看能不能真正解决问题

感觉这样修改会跟速度有很大关系，

--------------------------------------------
我现在的环境是
cosyvoice 使用的是，这个 commit， 要是拉取最新的代码，跑不起来，这里有说明  https://github.com/qi-hua/async_cosyvoice/issues/50
commit 5788aa0c6a1aa14657c5f3d83896b00f9d6341e0
Author: hexisyztem <hexisyztem@icloud.com>
Date:   Tue Apr 1 17:37:49 2025 +0800

    Update file_utils.py
    
    reduce GPU memory cost


asyc_cosyvoice 使用的是，这个 commit, 确实有点旧，查看了最近的更改，貌似没有对这个非法内存访问的问题更改
commit d11f55f5a42a82d1c0e590adec3fddb7f1c628a5
Author: qihua <qihua147@qq.com>
Date:   Tue Apr 1 21:53:53 2025 +0800

    build: 提前开启 VLLM v1 模式
    
    - 此修改旨在确保在导入 VLLM 前，环境变量 VLLM_USE_V1 以启用 VLLM v1 版本

------------------------------------------------

现在程序 在 24G显存， 4090 上   2个 estimator 实例， 使用显存 15～16G，还有很多富裕
# tensorrt 使用的 10.0.1
tensorrt-cu12==10.0.1
tensorrt-cu12-bindings==10.0.1
tensorrt-cu12-libs==10.0.1

我在对应的函数 async def inference_*  内部添加了 torch.cuda.empty_cache()  代码， 显存不会明显增加


------------------------------------------------




然后我写了个压测脚本，不断的重启服务，然后 4～16 个线程循环调用，

在 log 中能查到 RuntimeError: CUDA error: an illegal memory access was encountered 之类的问题


当然还有偶发的其他问题 ,这可能是由于 非法内存访问造成的
```
ERROR ForcedTermination, RuntimeError failed: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/cosyvoice/transformer/upsample_encoder/___torch_mangle_32.py", line 131, in forward
    outputs = torch.contiguous(torch.transpose(x, 1, 2))
    outputs0 = torch.pad(outputs, [0, 3], "constant", 0.)
    _50 = torch.conv1d(outputs0, CONSTANTS.c5, CONSTANTS.c6)
          ~~~~~~~~~~~~ <--- HERE
    result = torch.leaky_relu(_50)
    outputs1 = torch.pad(result, [2, 0], "constant", 0.)

Traceback of TorchScript, original code (most recent call last):
  File "/mnt/lyuxiang.lx/anaconda3/envs/cosyvoice2.0/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in forward
                            weight, bias, self.stride,
                            _single(0), self.dilation, self.groups)
        return F.conv1d(input, weight, bias, self.stride,
               ~~~~~~~~ <--- HERE
                        self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [512, 512, 4], expected input[0, 0, 3] to have 512 channels, but got 0 channels instead
```
----------------------------------------------------
另外引用，五一期间，@Artrajz 的评论 

我这边在async_tts最后用 finally 添加torch.cuda.empty_cache()，使用estimator_count=1，Estimator context 的显存占用没改，在长时间运行后仍有概率会出现这个问题，从正常开始运行到出问题的时间不固定（复现可能存在困难）。显卡是4090 24g的，运行时显存占用稳定在21500MB以下。出现这个问题后通常会导致其他请求任务也无法正常推理，目前我只能通过不断重启来解决。

这是我这边的情况，希望能辅助大佬分析问题

貌似这个错误，跟estimator_count的数量，也没有很大的关系

**Comment by hexisyztem** [comment]
> > 你们这里提到的问题比较像是之前修复过的一个问题，确认是拉取了最新的代码吗？
> 
> 您指的是model里面针对末尾6561 之类的处理那次更改吗。

 @CallmeZhangChenchen 
是的，这个修复了“可能造成运行崩溃”的问题

**Comment by hexisyztem** [comment]
> [@hexisyztem](https://github.com/hexisyztem) 感谢回复！ 我尽量把问题描述清楚
> 
> 我们上午在讨论如何避免 RuntimeError 错误发生的问题， 提到 “ 将model.py 中的thread_count=10 中的这个子线程改成1 就不会再出现”，这个我将会测试看看能不能真正解决问题
> 
> 感觉这样修改会跟速度有很大关系，
> 
> 我现在的环境是 cosyvoice 使用的是，这个 commit， 要是拉取最新的代码，跑不起来，这里有说明 [#50](https://github.com/qi-hua/async_cosyvoice/issues/50) commit 5788aa0c6a1aa14657c5f3d83896b00f9d6341e0 Author: hexisyztem [hexisyztem@icloud.com](mailto:hexisyztem@icloud.com) Date: Tue Apr 1 17:37:49 2025 +0800
> 
> ```
> Update file_utils.py
> 
> reduce GPU memory cost
> ```
> 
> asyc_cosyvoice 使用的是，这个 commit, 确实有点旧，查看了最近的更改，貌似没有对这个非法内存访问的问题更改 commit [d11f55f](https://github.com/qi-hua/async_cosyvoice/commit/d11f55f5a42a82d1c0e590adec3fddb7f1c628a5) Author: qihua [qihua147@qq.com](mailto:qihua147@qq.com) Date: Tue Apr 1 21:53:53 2025 +0800
> 
> ```
> build: 提前开启 VLLM v1 模式
> 
> - 此修改旨在确保在导入 VLLM 前，环境变量 VLLM_USE_V1 以启用 VLLM v1 版本
> ```
> 
> 现在程序 在 24G显存， 4090 上 2个 estimator 实例， 使用显存 15～16G，还有很多富裕
> 
> # tensorrt 使用的 10.0.1
> tensorrt-cu12==10.0.1 tensorrt-cu12-bindings==10.0.1 tensorrt-cu12-libs==10.0.1
> 
> 我在对应的函数 async def inference_* 内部添加了 torch.cuda.empty_cache() 代码， 显存不会明显增加
> 
> 然后我写了个压测脚本，不断的重启服务，然后 4～16 个线程循环调用，
> 
> 在 log 中能查到 RuntimeError: CUDA error: an illegal memory access was encountered 之类的问题
> 
> 当然还有偶发的其他问题 ,这可能是由于 非法内存访问造成的
> 
> ```
> ERROR ForcedTermination, RuntimeError failed: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript, serialized code (most recent call last):
>   File "code/__torch__/cosyvoice/transformer/upsample_encoder/___torch_mangle_32.py", line 131, in forward
>     outputs = torch.contiguous(torch.transpose(x, 1, 2))
>     outputs0 = torch.pad(outputs, [0, 3], "constant", 0.)
>     _50 = torch.conv1d(outputs0, CONSTANTS.c5, CONSTANTS.c6)
>           ~~~~~~~~~~~~ <--- HERE
>     result = torch.leaky_relu(_50)
>     outputs1 = torch.pad(result, [2, 0], "constant", 0.)
> 
> Traceback of TorchScript, original code (most recent call last):
>   File "/mnt/lyuxiang.lx/anaconda3/envs/cosyvoice2.0/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in forward
>                             weight, bias, self.stride,
>                             _single(0), self.dilation, self.groups)
>         return F.conv1d(input, weight, bias, self.stride,
>                ~~~~~~~~ <--- HERE
>                         self.padding, self.dilation, self.groups)
> RuntimeError: Given groups=1, weight of size [512, 512, 4], expected input[0, 0, 3] to have 512 channels, but got 0 channels instead
> ```
> 
> 另外引用，五一期间，[@Artrajz](https://github.com/Artrajz) 的评论
> 
> 我这边在async_tts最后用 finally 添加torch.cuda.empty_cache()，使用estimator_count=1，Estimator context 的显存占用没改，在长时间运行后仍有概率会出现这个问题，从正常开始运行到出问题的时间不固定（复现可能存在困难）。显卡是4090 24g的，运行时显存占用稳定在21500MB以下。出现这个问题后通常会导致其他请求任务也无法正常推理，目前我只能通过不断重启来解决。
> 
> 这是我这边的情况，希望能辅助大佬分析问题
> 
> 貌似这个错误，跟estimator_count的数量，也没有很大的关系

看你的报错，应该就是09a4eb7160ca9e3dec35726e63a13edd3c376a75 修复的问题。

**Comment by CallmeZhangChenchen** [comment]
@hexisyztem  好的 感谢🙏🙏， 我们测试一下

**Comment by hexisyztem** [comment]
> [@hexisyztem](https://github.com/hexisyztem) 好的 感谢🙏🙏， 我们测试一下

https://github.com/qi-hua/async_cosyvoice/issues/50 这里这个提到的问题，主要是我之前不小心把我的仓库重置了，导致你们运行出了点问题，可以把 Cosyvoice 的flow_matching.py 文件直接替换成 https://github.com/FunAudioLLM/CosyVoice/blob/dev/Comet/cosyvoice/flow/flow_matching.py 这里的。

**Comment by Artrajz** [comment]
@CallmeZhangChenchen 发出去之后我想把报错贴上来，然后发现报错的代码位置不太一样，怕不是同一个问题所以就删了。


刚刚用之前的代码压测了一下，用1个estimator和修改
`config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30) # 1GB`
删除旧的fp16.mygpu.plan重新生成

压测出现了这个错误，报错位置和你的有点不一样
```
2025-05-06 17:10:26 | ERROR    | model:415 - async_tts: Traceback (most recent call last):
  File "/data/CosyVoice/async_cosyvoice/model.py", line 394, in async_tts
    # deal with all tokens
  File "/data/CosyVoice/async_cosyvoice/model.py", line 197, in llm_job
    prompt_text = tensor_to_list(prompt_text + torch.tensor(6564))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-05-06 17:10:26 | ERROR    | async_cosyvoice:108 - yield speech error: Traceback (most recent call last):
  File "/data/CosyVoice/async_cosyvoice/async_cosyvoice.py", line 101, in inference_sft
    speech_len = model_output['tts_speech'].shape[1] / self.sample_rate
TypeError: 'NoneType' object is not subscriptable

  0%|                                                                                                                                                                                                   | 0/1 [00:00<?, ?it/s]
2025-05-06 17:10:26 | ERROR    | app:295 - [inference_sft] Traceback (most recent call last):
  File "/data/CosyVoice/app.py", line 259, in inference_sft
    async for chunk in model_output_gen:
  File "/data/CosyVoice/async_cosyvoice/async_cosyvoice.py", line 99, in inference_sft
    async for model_output in self.model.async_tts(**model_input, stream=stream, speed=speed):
  File "/data/CosyVoice/async_cosyvoice/model.py", line 422, in async_tts
    self.hift_cache_dict.pop(this_uuid)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/cuda/memory.py", line 192, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

然后下面是之前的报错日志
```
2025-04-28 13:39:37 | ERROR    | model:411 - async_tts: Traceback (most recent call last):
  File "/data/CosyVoice/async_cosyvoice/model.py", line 394, in async_tts
    await llm_task
  File "/data/CosyVoice/async_cosyvoice/model.py", line 197, in llm_job
    prompt_text = tensor_to_list(prompt_text + torch.tensor(6564))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2025-04-28 13:39:37 | ERROR    | async_cosyvoice:108 - yield speech error: Traceback (most recent call last):
  File "/data/CosyVoice/async_cosyvoice/async_cosyvoice.py", line 101, in inference_sft
    speech_len = model_output['tts_speech'].shape[1] / self.sample_rate
TypeError: 'NoneType' object is not subscriptable

2025-04-28 13:39:37 | ERROR    | app:293 - [inference_sft] Traceback (most recent call last):
  File "/data/CosyVoice/app.py", line 259, in inference_sft
    async for chunk in model_output_gen:
  File "/data/CosyVoice/async_cosyvoice/async_cosyvoice.py", line 99, in inference_sft
    async for model_output in self.model.async_tts(**model_input, stream=stream, speed=speed):
  File "/data/CosyVoice/async_cosyvoice/model.py", line 418, in async_tts
    torch.cuda.empty_cache()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/cuda/memory.py", line 192, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

我也试试大佬修复的代码

**Comment by CallmeZhangChenchen** [comment]
@hexisyztem  大佬 ，试了下这个commit  09a4eb7160ca9e3dec35726e63a13edd3c376a75 ，
测试一晚上，（不断的重启服务 4 个线程调用），有 20 多次复现 🥲，看来不并不是这个原因

RuntimeError failed: CUDA error: an illegal memory access was encountered
RuntimeError failed: The following operation failed in the TorchScript interpreter.

**Comment by CallmeZhangChenchen** [comment]
@Artrajz  你这个错误我见过， 感觉应该是你 torch.cuda.empty_cache()  写错位置了，导致了这个错误 
你可以写 这里， 可以比着改一下，

```
async def inference_zero_shot_by_spk_id(self, tts_text, spk_id, stream=False, speed=1.0, text_frontend=True):
        """使用预定义的说话人执行 zero_shot 推理"""
        try:
            for i in tqdm(self.frontend.text_normalize(tts_text, split=True, text_frontend=text_frontend)):
                model_input = self.frontend.frontend_zero_shot_by_spk_id(i, spk_id)
                start_time = time.time()
                last_time = start_time
                chunk_index = 0
                logging.info('synthesis text {}'.format(i))
                async for model_output in self.model.async_tts(**model_input, stream=stream, speed=speed):
                    speech_len = model_output['tts_speech'].shape[1] / self.sample_rate
                    logging.info('yield speech index:{}, len {:.2f}, rtf {:.3f},  cost {:.3f}s,  all cost time {:.3f}s'.format(
                        chunk_index, speech_len,  (time.time()-last_time)/speech_len, time.time()-last_time, time.time()-start_time))
                    yield model_output
                    last_time = time.time()
                    chunk_index += 1
            # torch.cuda.empty_cache()
        except RuntimeError as e:
            logging.error(f"ForcedTermination, RuntimeError failed: {str(e)}", exc_info=True)
            import os
            os.system('pkill python')
            os._exit(1)
```

**Comment by CallmeZhangChenchen** [comment]
> [@hexisyztem](https://github.com/hexisyztem) 大佬 ，试了下这个commit [09a4eb7](https://github.com/qi-hua/async_cosyvoice/commit/09a4eb7160ca9e3dec35726e63a13edd3c376a75) ， 测试一晚上，（不断的重启服务 4 个线程调用），有 20 多次复现 🥲，看来不并不是这个原因
> 
> RuntimeError failed: CUDA error: an illegal memory access was encountered RuntimeError failed: The following operation failed in the TorchScript interpreter.

贴一下日志文件

通过百度网盘分享的文件：test0506....text
链接：https://pan.baidu.com/s/1tWKi0nls5rgWA56V_SSNVQ?pwd=7H5u 
提取码：7H5u 
复制这段内容打开「百度网盘APP 即可获取」

**Comment by Artrajz** [comment]
@CallmeZhangChenchen 好的感谢！我试试，请问意思是应该在`inference_zero_shot_by_spk_id`后面写`torch.cuda.empty_cache()`对吗？我原本是在aysnc_tts函数的最后面添加的：
```
          async with self.lock:
              self.tts_speech_token_dict.pop(this_uuid)
              self.llm_end_dict.pop(this_uuid)
              self.hift_cache_dict.pop(this_uuid)
          torch.cuda.empty_cache()
```

**Comment by brooks348** [comment]
> > [@hexisyztem](https://github.com/hexisyztem) 大佬 ，试了下这个commit [09a4eb7](https://github.com/qi-hua/async_cosyvoice/commit/09a4eb7160ca9e3dec35726e63a13edd3c376a75) ， 测试一晚上，（不断的重启服务 4 个线程调用），有 20 多次复现 🥲，看来不并不是这个原因
> > RuntimeError failed: CUDA error: an illegal memory access was encountered RuntimeError failed: The following operation failed in the TorchScript interpreter.
> 
> 贴一下日志文件
> 
> 通过百度网盘分享的文件：test0506....text 链接：https://pan.baidu.com/s/1tWKi0nls5rgWA56V_SSNVQ?pwd=7H5u 提取码：7H5u 复制这段内容打开「百度网盘APP 即可获取」

运行时有没有打开fp16,jit，trt这三个选项？，我发现我这边打开配置是没有问题的，不打开这三个配置会报错。

**Comment by CharonMing** [comment]
# 修改后的关键代码段
async def llm_job(self, text, prompt_text, llm_prompt_speech_token, llm_embedding, uuid):
    # 确保张量在相同设备
    device = prompt_text.device
    prompt_text = tensor_to_list(prompt_text + torch.tensor(6564, device=device))
    llm_prompt_speech_token = tensor_to_list(llm_prompt_speech_token.to(device))

    # ...其余代码保持不变...

**Comment by CharonMing** [comment]
#  修改后的关键代码段 llm_job
    async def llm_job(self, text, prompt_text, llm_prompt_speech_token, llm_embedding, uuid):
      # 确保张量在相同设备
    device = prompt_text.device
    prompt_text = tensor_to_list(prompt_text + torch.tensor(6564, device=device))
    llm_prompt_speech_token = tensor_to_list(llm_prompt_speech_token.to(device))

    # ...其余代码保持不变...


# 在async_tts函数开始时确保输入设备正确
    async def async_tts(self, text, flow_embedding, llm_embedding=torch.zeros(0, 192),
                    prompt_text=torch.zeros(1, 0, dtype=torch.int32),
                    llm_prompt_speech_token=torch.zeros(1, 0, dtype=torch.int32),
                    flow_prompt_speech_token=torch.zeros(1, 0, dtype=torch.int32),
                    prompt_speech_feat=torch.zeros(1, 0, 80), stream=False, speed=1.0, **kwargs):
    
    # 显式将输入张量移至CPU
    prompt_text = prompt_text.cpu()
    llm_prompt_speech_token = llm_prompt_speech_token.cpu()
    flow_prompt_speech_token = flow_prompt_speech_token.to(self.device)
    prompt_speech_feat = prompt_speech_feat.to(self.device)

    # ...其余代码保持不变...


# ​​资源清理与同步
    def token2wav(self, token, prompt_token, prompt_feat, embedding, uuid, token_offset, finalize=False, speed=1.0):
        torch.cuda.empty_cache()
        torch.cuda.synchronize()  
    
        # ...其余代码保持不变...
    
            torch.cuda.synchronize(stream)
    
        self.stream_pool.put(stream)
        return tts_speech

@CallmeZhangChenchen 我改了几句代码，压测之后没有复现了 thread_count = 4

**Comment by CallmeZhangChenchen** [comment]
好的，太感谢了🙏 🙏，我也试试！

token2wav 函数是这样写的哈！ 
```
def token2wav(self, token, prompt_token, prompt_feat, embedding, uuid, token_offset, finalize=False, speed=1.0):
        torch.cuda.empty_cache()
        torch.cuda.synchronize()
       
        stream = self.stream_pool.get()
        with torch.cuda.stream(stream):

            # ...其余代码保持不变...

            torch.cuda.synchronize(stream)
            self.stream_pool.put(stream)
            return tts_speech
```

**Comment by wblgers** [comment]
> # 修改后的关键代码段 llm_job
> ```
> async def llm_job(self, text, prompt_text, llm_prompt_speech_token, llm_embedding, uuid):
>   # 确保张量在相同设备
> device = prompt_text.device
> prompt_text = tensor_to_list(prompt_text + torch.tensor(6564, device=device))
> llm_prompt_speech_token = tensor_to_list(llm_prompt_speech_token.to(device))
> 
> # ...其余代码保持不变...
> ```
> 
> # 在async_tts函数开始时确保输入设备正确
> ```
> async def async_tts(self, text, flow_embedding, llm_embedding=torch.zeros(0, 192),
>                 prompt_text=torch.zeros(1, 0, dtype=torch.int32),
>                 llm_prompt_speech_token=torch.zeros(1, 0, dtype=torch.int32),
>                 flow_prompt_speech_token=torch.zeros(1, 0, dtype=torch.int32),
>                 prompt_speech_feat=torch.zeros(1, 0, 80), stream=False, speed=1.0, **kwargs):
> 
> # 显式将输入张量移至CPU
> prompt_text = prompt_text.cpu()
> llm_prompt_speech_token = llm_prompt_speech_token.cpu()
> flow_prompt_speech_token = flow_prompt_speech_token.to(self.device)
> prompt_speech_feat = prompt_speech_feat.to(self.device)
> 
> # ...其余代码保持不变...
> ```
> 
> # ​​资源清理与同步
> ```
> def token2wav(self, token, prompt_token, prompt_feat, embedding, uuid, token_offset, finalize=False, speed=1.0):
>     torch.cuda.empty_cache()
>     torch.cuda.synchronize()  
> 
>     # ...其余代码保持不变...
> 
>         torch.cuda.synchronize(stream)
> 
>     self.stream_pool.put(stream)
>     return tts_speech
> ```
> 
> [@CallmeZhangChenchen](https://github.com/CallmeZhangChenchen) 我改了几句代码，压测之后没有复现了 thread_count = 4

请问 token2wav里面原本的这两句是需要去掉吗？
torch.cuda.current_stream().synchronize()

torch.cuda.synchronize(torch.cuda.current_stream())

**Comment by frontword** [comment]
> # 修改后的关键代码段 llm_job
> ```
> async def llm_job(self, text, prompt_text, llm_prompt_speech_token, llm_embedding, uuid):
>   # 确保张量在相同设备
> device = prompt_text.device
> prompt_text = tensor_to_list(prompt_text + torch.tensor(6564, device=device))
> llm_prompt_speech_token = tensor_to_list(llm_prompt_speech_token.to(device))
> 
> # ...其余代码保持不变...
> ```
> 
> # 在async_tts函数开始时确保输入设备正确
> ```
> async def async_tts(self, text, flow_embedding, llm_embedding=torch.zeros(0, 192),
>                 prompt_text=torch.zeros(1, 0, dtype=torch.int32),
>                 llm_prompt_speech_token=torch.zeros(1, 0, dtype=torch.int32),
>                 flow_prompt_speech_token=torch.zeros(1, 0, dtype=torch.int32),
>                 prompt_speech_feat=torch.zeros(1, 0, 80), stream=False, speed=1.0, **kwargs):
> 
> # 显式将输入张量移至CPU
> prompt_text = prompt_text.cpu()
> llm_prompt_speech_token = llm_prompt_speech_token.cpu()
> flow_prompt_speech_token = flow_prompt_speech_token.to(self.device)
> prompt_speech_feat = prompt_speech_feat.to(self.device)
> 
> # ...其余代码保持不变...
> ```
> 
> # ​​资源清理与同步
> ```
> def token2wav(self, token, prompt_token, prompt_feat, embedding, uuid, token_offset, finalize=False, speed=1.0):
>     torch.cuda.empty_cache()
>     torch.cuda.synchronize()  
> 
>     # ...其余代码保持不变...
> 
>         torch.cuda.synchronize(stream)
> 
>     self.stream_pool.put(stream)
>     return tts_speech
> ```
> 
> [@CallmeZhangChenchen](https://github.com/CallmeZhangChenchen) 我改了几句代码，压测之后没有复现了 thread_count = 4

@CharonMing 按照你的方法修改测试后，还是会遇到这个错误，请贴下你那里这3个函数(llm_job, async_tts, token2wav)完整的代码，我比较下是否哪里和你修改的不一样，另外，请告诉下你那里用的cuda的版本号和torch的版本号分别是多少

**Comment by CharonMing** [comment]
cuda 12.4  torch 2.5.1 @CallmeZhangChenchen

**Comment by CallmeZhangChenchen** [comment]
抱歉耽误大家时间了！ 
问题出现的原因找到了，工程代码没有任何问题，很稳定
可能的原因：由于自己的原因，服务在 ctrl+C 之后或者错误的停止方式，会导致容器内部显存碎片有一些问题，从而影响下次服务的稳定性， 
建议：假如发现这个问题之后，建议重启一下容器

**Comment by wenyangchou** [comment]
> # 修改后的关键代码段 llm_job
> ```
> async def llm_job(self, text, prompt_text, llm_prompt_speech_token, llm_embedding, uuid):
>   # 确保张量在相同设备
> device = prompt_text.device
> prompt_text = tensor_to_list(prompt_text + torch.tensor(6564, device=device))
> llm_prompt_speech_token = tensor_to_list(llm_prompt_speech_token.to(device))
> 
> # ...其余代码保持不变...
> ```
> 
> # 在async_tts函数开始时确保输入设备正确
> ```
> async def async_tts(self, text, flow_embedding, llm_embedding=torch.zeros(0, 192),
>                 prompt_text=torch.zeros(1, 0, dtype=torch.int32),
>                 llm_prompt_speech_token=torch.zeros(1, 0, dtype=torch.int32),
>                 flow_prompt_speech_token=torch.zeros(1, 0, dtype=torch.int32),
>                 prompt_speech_feat=torch.zeros(1, 0, 80), stream=False, speed=1.0, **kwargs):
> 
> # 显式将输入张量移至CPU
> prompt_text = prompt_text.cpu()
> llm_prompt_speech_token = llm_prompt_speech_token.cpu()
> flow_prompt_speech_token = flow_prompt_speech_token.to(self.device)
> prompt_speech_feat = prompt_speech_feat.to(self.device)
> 
> # ...其余代码保持不变...
> ```
> 
> # ​​资源清理与同步
> ```
> def token2wav(self, token, prompt_token, prompt_feat, embedding, uuid, token_offset, finalize=False, speed=1.0):
>     torch.cuda.empty_cache()
>     torch.cuda.synchronize()  
> 
>     # ...其余代码保持不变...
> 
>         torch.cuda.synchronize(stream)
> 
>     self.stream_pool.put(stream)
>     return tts_speech
> ```
> 
> [@CallmeZhangChenchen](https://github.com/CallmeZhangChenchen) 我改了几句代码，压测之后没有复现了 thread_count = 4

应该就是这个原因。但是这个会是在什么情况导致他们一个用cpu、一个用gpu？偶现，啥机制，在什么场景会触发这种问题？

**Comment by tujie-jiangye** [comment]
> 抱歉耽误大家时间了！ 问题出现的原因找到了，工程代码没有任何问题，很稳定 可能的原因：由于自己的原因，服务在 ctrl+C 之后或者错误的停止方式，会导致容器内部显存碎片有一些问题，从而影响下次服务的稳定性， 建议：假如发现这个问题之后，建议重启一下容器


@CallmeZhangChenchen 请问有解决这个问题吗，我按照上边的所有方法都操作了一遍，依然还是不行

**Comment by developer-hq** [comment]
4个线程我也跑通了，但是调大线程数10个 16个都不行，还是会出现显存访问错误的bug，有大佬知道这是什么原因吗
